#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# from setuptools import setup

# APP = ['main.py']
# DATA_FILES = []
# OPTIONS = {}

# setup(
#     app=APP,
#     data_files=DATA_FILES,
#     options={'py2app': OPTIONS},
#     setup_requires=['py2app'],
# )


def ssss(ni="123"):
    print(ni)


if __name__ == "__main__":

    ssss(None)